spring:
  application:
    name: service2
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}
  instance:
    preferIpAddress: true
#server:
#  port: 9082
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8302/eureka